import {
  ChatbubblesOutline, HeartOutline, HomeOutline, LibraryOutline, RocketOutline, ShirtOutline,
  ThumbsUpOutline, BulbOutline, CashOutline, MegaphoneOutline, FlashOutline, BrushOutline,
  HappyOutline, EarthOutline, BookmarkOutline, MicOutline, BeerOutline, BookOutline,
  ThumbsDownOutline, PhonePortraitOutline, CompassOutline, GlassesOutline, BandageOutline,
  SkullOutline, PawOutline,
} from 'react-ionicons';

export const iconsByName = {
  'heart-outline': <HeartOutline />,
  'home-outline': <HomeOutline />,
  'rocket-outline': <RocketOutline />,
  'chatbubbles-outline': <ChatbubblesOutline />,
  'library-outline': <LibraryOutline />,
  'shirt-outline': <ShirtOutline />,
  'thumbs-up-outline': <ThumbsUpOutline />,
  'bulb-outline': <BulbOutline />,
  'cash-outline': <CashOutline />,
  'megaphone-outline': <MegaphoneOutline />,
  'flash-outline': <FlashOutline />,
  'brush-outline': <BrushOutline />,
  'happy-outline': <HappyOutline />,
  'earth-outline': <EarthOutline />,
  'bookmark-outline': <BookmarkOutline />,
  'mic-outline': <MicOutline />,
  'beer-outline': <BeerOutline />,
  'book-outline': <BookOutline />,
  'thumbs-down-outline': <ThumbsDownOutline />,
  'phone-outline': <PhonePortraitOutline />,
  'compass-outline': <CompassOutline />,
  'glasses-outline': <GlassesOutline />,
  'bandage-outline': <BandageOutline />,
  'skull-outline': <SkullOutline />,
  'paw-outline': <PawOutline />,
}